### ISSUE TITLE
I can't get the basic Journal to Canvas functions to work

### ISSUE THREAD

**Issue by DocArcane** [EvanesceExotica/Journal-To-Canvas-Slideshow#45]
Since upgrading to FVTT v10 I've lost the basic functions I was using Journal to Canvas for. Even after upgrading to the latest release (0.2.4) I can't get the core "click on an image in a journal - and have it appear on the canvas" to function. Below is a link to a YouTube video I made 8 months ago when the mod worked perfectly - https://www.youtube.com/watch?v=RZdrNfJMtjs&t=7s

The new UI is confusing and nothing I've tried seems to get me back to the basic function of "Journal to Canvas". Is this no longer the intended use?

**Comment by 4Sora21** [comment]
After 2 hours of trying. I found out that they have a little purple UI option on the right bottom corner of every journal to toggle the imagine control of that journal. And everyone's favorite mod "Monk's enchanted journal" will completely block out that UI. So all you need to do is to turn off the "Monk's enchanted journal" and toggle on the imagine control of that journal, after that turn back on the "Monk's enchanted journal" and here you go that journal is fixed.

**Comment by DocArcane** [comment]
I'll give that a try

**Comment by Evannessa** [comment]
@DocArcane  I'm so sorry that you're having these issues and are finding things confusing. :( 

The module underwent a huge overhaul which added a lot of quality of life features, customization options, and controls, and is a big change from how things used to work, but the core functionality is still the same, and the basic "click an image in a journal to show it on the tile" feature is still in there! That functionality will always be the core feature of this module.

The module now has a few compendiums, one of which has pre-made scenes in them that you can import into your world.

![Compendium](https://user-images.githubusercontent.com/13098820/203420633-71668cb2-5190-40ba-80d1-e1d2f29c0542.png)

If you import the one called "Display", it will already have a scene with "Gallery Tiles" created and placed for you. 

But I put together a quick step-by-step walk-through to explain how to create one from scratch:

![FromScratchStepByStep](https://user-images.githubusercontent.com/13098820/203411616-2bc5b04c-5633-4082-a5bc-45a260c9cb6c.png)

And another two quick step-by-steps on how to toggle the controls" on and off for the different types of sheets" in the JTCS Settings Application an on the individual sheets themselves.

![SettingsStepByStep](https://user-images.githubusercontent.com/13098820/203419605-0fb32ea6-07b6-41fb-9cad-fcf75e5b2b0b.png)

![SheetToggleStepbyStep](https://user-images.githubusercontent.com/13098820/203419637-dfe8e923-e7f8-4b91-836d-ea990c83bc85.png)

In addition, here's a page that walks through all of the new features and changes, and it may be really helpful to take a look through it.

https://github.com/Evannessa/Journal-To-Canvas-Slideshow/blob/master/features-and-walkthrough.md

It's also possible like @4Sora21 mentioned, the journal controls are being hidden by another module like Monk's Enhanced Journal, so if you aren't able to see the controls *at all*, it might help to try out my module in a blank world with no other modules installed and see if you're able to see it then.

 If you have any questions about anything specifically that is confusing for you, I'd be happy to answer!

@4Sora21 Thanks so much for letting me know that Monks Enhanced Journal has a conflict with my module; I'm going to take a look when I have time to see if I can change the location (or allow custom placement) so the controls aren't hidden.

**Comment by DocArcane** [comment]
For the record - it _was_ the conflict with Enhanced Journals that was preventing the Image Controls Toggle from appearing in the bottom corner

**Comment by Evannessa** [comment]
Ah, okay! Thanks for the update! I'll add a fix for that in my next update ^ ^
